src = ["src"]
exclude = [".venv"]
fix = true
line-length = 140

[format]
quote-style = "double"
docstring-code-format = true
skip-magic-trailing-comma = false
line-ending = "auto"

[lint]
extend-select = ["I"]

[lint.isort]
force-wrap-aliases = true
combine-as-imports = true
order-by-type = true
known-first-party = ["src"]