"""Factory helpers for building test domain objects without factory_boy.

Each function returns a domain object with sensible defaults generated by Faker.
Use the `**overrides` parameter to override specific fields for a given test case.
"""

from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

from faker import Faker

from src.auth.domain.entities import UserEntity
from src.market.domain.entities.buyers import BuyerEntity
from src.market.domain.entities.sales import SaleEntity
from src.market.domain.value_objects.buyer_value_objects import (
    BuyerCreateValueObject,
    BuyerUpdateValueObject,
)
from src.market.domain.value_objects.sale_value_objects import (
    SaleCreateValueObject,
    SaleListQueryParamsValueObject,
)

_faker = Faker()


def make_sale_create(**overrides: Any) -> SaleCreateValueObject:
    """Build a SaleCreateValueObject with realistic defaults."""
    price = round(float(_faker.pydecimal(min_value=100, max_value=5000, right_digits=2)), 2)
    weight = round(float(_faker.pydecimal(min_value=50, max_value=500, right_digits=2)), 2)
    defaults = dict(
        user_id=uuid4(),
        animal_id=uuid4(),
        buyer_id=uuid4(),
        sale_date=_faker.date_between(start_date="-1y"),
        price=price,
        price_per_kg=round(price / weight + float(_faker.pydecimal(min_value=1, max_value=10, right_digits=2)), 2),
        weight=weight,
        description=_faker.sentence(nb_words=8),
    )
    defaults.update(overrides)
    return SaleCreateValueObject(**defaults)


def make_sale_entity(**overrides: Any) -> SaleEntity:
    """Build a SaleEntity with realistic defaults."""
    price = round(float(_faker.pydecimal(min_value=100, max_value=5000, right_digits=2)), 2)
    weight = round(float(_faker.pydecimal(min_value=50, max_value=500, right_digits=2)), 2)
    defaults = dict(
        id=uuid4(),
        sale_date=_faker.date_between(start_date="-1y"),
        price=price,
        price_per_kg=round(price / weight + float(_faker.pydecimal(min_value=1, max_value=10, right_digits=2)), 2),
        weight=weight,
        description=_faker.sentence(nb_words=8),
    )
    defaults.update(overrides)
    return SaleEntity(**defaults)


def make_sale_list_params(**overrides: Any) -> SaleListQueryParamsValueObject:
    """Build a SaleListQueryParamsValueObject with no filters by default."""
    defaults: dict[str, Any] = {}
    defaults.update(overrides)
    return SaleListQueryParamsValueObject(**defaults)


def make_buyer_create(**overrides: Any) -> BuyerCreateValueObject:
    """Build a BuyerCreateValueObject with realistic defaults."""
    defaults = dict(
        user_id=uuid4(),
        name=_faker.company(),
        description=_faker.catch_phrase(),
        contact_number=_faker.phone_number(),
        contact_address=_faker.address(),
    )
    defaults.update(overrides)
    return BuyerCreateValueObject(**defaults)


def make_buyer_update(**overrides: Any) -> BuyerUpdateValueObject:
    """Build a BuyerUpdateValueObject with no fields set by default."""
    defaults: dict[str, Any] = {}
    defaults.update(overrides)
    return BuyerUpdateValueObject(**defaults)


def make_buyer_entity(**overrides: Any) -> BuyerEntity:
    """Build a BuyerEntity with realistic defaults."""
    defaults = dict(
        id=uuid4(),
        created_at=datetime.now(tz=timezone.utc),
        name=_faker.company(),
        description=_faker.catch_phrase(),
        contact_number=_faker.phone_number(),
        contact_address=_faker.address(),
    )
    defaults.update(overrides)
    return BuyerEntity(**defaults)


def make_user_entity(**overrides: Any) -> UserEntity:
    """Build a UserEntity with realistic defaults."""
    defaults = dict(
        id=uuid4(),
        name=_faker.name(),
        dni=_faker.unique.numerify(text="########"),
        email=_faker.unique.email(),
        created_at=datetime.now(tz=timezone.utc),
        is_admin=False,
        _hashed_password=_faker.sha256(),
    )
    defaults.update(overrides)
    return UserEntity(**defaults)


# ── Cattle: Animal ────────────────────────────────────────────────────

from src.cattle.domain.constants.animal import AnimalStatus  # noqa: E402
from src.cattle.domain.entities.animal_entity import AnimalEntity as AnimalEntity_  # noqa: E402
from src.cattle.domain.value_objects.animal_value_object import (  # noqa: E402
    AnimalCreateValueObject as AnimalCreateVO,
    AnimalsListQueryParamsValueObject as AnimalsListParamsVO,
    AnimalUpdateValueObject as AnimalUpdateVO,
)


def make_animal_create(**overrides: Any) -> AnimalCreateVO:
    """Build an AnimalCreateValueObject with realistic defaults."""
    defaults = dict(
        user_id=uuid4(),
        type_id=uuid4(),
        caravana=_faker.unique.bothify(text="CAR-??????"),
        breed=_faker.word(),
        tag=_faker.unique.bothify(text="TAG-??????"),
        date_of_birth=_faker.date_between(start_date="-3y", end_date="-1y"),
        initial_weight=round(float(_faker.pydecimal(min_value=100, max_value=300, right_digits=2)), 2),
        initial_weight_date=_faker.date_between(start_date="-3y", end_date="-1y"),
        last_weight=round(float(_faker.pydecimal(min_value=200, max_value=500, right_digits=2)), 2),
        status=AnimalStatus.NOT_READY,
    )
    defaults.update(overrides)
    return AnimalCreateVO(**defaults)


def make_animal_entity(**overrides: Any) -> AnimalEntity_:
    """Build an AnimalEntity with realistic defaults."""
    defaults = dict(
        id=uuid4(),
        caravana=_faker.unique.bothify(text="CAR-??????"),
        tag=_faker.unique.bothify(text="TAG-??????"),
        date_of_birth=_faker.date_between(start_date="-3y", end_date="-1y"),
        initial_weight=round(float(_faker.pydecimal(min_value=100, max_value=300, right_digits=2)), 2),
        initial_weight_date=_faker.date_between(start_date="-3y", end_date="-1y"),
        last_weight=round(float(_faker.pydecimal(min_value=200, max_value=500, right_digits=2)), 2),
        breed=_faker.word(),
        status=AnimalStatus.NOT_READY,
    )
    defaults.update(overrides)
    return AnimalEntity_(**defaults)


def make_animal_list_params(**overrides: Any) -> AnimalsListParamsVO:
    """Build AnimalsListQueryParamsValueObject with no filters by default."""
    defaults: dict[str, Any] = {}
    defaults.update(overrides)
    return AnimalsListParamsVO(**defaults)


def make_animal_update(**overrides: Any) -> AnimalUpdateVO:
    """Build an AnimalUpdateValueObject with minimal defaults."""
    defaults = dict(
        user_id=uuid4(),
        type_id=uuid4(),
    )
    defaults.update(overrides)
    return AnimalUpdateVO(**defaults)


# ── Cattle: Animal Types ──────────────────────────────────────────────

from src.cattle.domain.entities.animal_entity import AnimalTypeEntity  # noqa: E402
from src.cattle.domain.value_objects.animal_type_value_object import (  # noqa: E402
    AnimalTypeCreateValueObject as AnimalTypeCreateVO,
    AnimalTypeListQueryParamsValueObject as AnimalTypeListParamsVO,
    AnimalTypeUpdateValueObject,
)


def make_animal_type_create(**overrides: Any) -> AnimalTypeCreateVO:
    """Build an AnimalTypeCreateValueObject."""
    defaults = dict(name=_faker.unique.word())
    defaults.update(overrides)
    return AnimalTypeCreateVO(**defaults)


def make_animal_type_entity(**overrides: Any) -> AnimalTypeEntity:
    """Build an AnimalTypeEntity."""
    defaults = dict(id=uuid4(), name=_faker.unique.word())
    defaults.update(overrides)
    return AnimalTypeEntity(**defaults)


def make_animal_type_list_params(**overrides: Any) -> AnimalTypeListParamsVO:
    """Build AnimalTypeListQueryParamsValueObject with no filters."""
    defaults: dict[str, Any] = {}
    defaults.update(overrides)
    return AnimalTypeListParamsVO(**defaults)


def make_animal_type_update(**overrides: Any) -> AnimalTypeUpdateValueObject:
    """Build an AnimalTypeUpdateValueObject."""
    defaults = dict(name=_faker.unique.word())
    defaults.update(overrides)
    return AnimalTypeUpdateValueObject(**defaults)


# ── Cattle: Animal Protocols ──────────────────────────────────────────

from src.cattle.domain.entities.animal_protocol_entity import AnimalProtocolEntity  # noqa: E402
from src.cattle.domain.value_objects.animal_protocol_value_object import (  # noqa: E402
    AnimalProtocolCreateValueObject as AnimalProtocolCreateVO,
    AnimalProtocolListQueryParamsValueObject as AnimalProtocolListParamsVO,
    AnimalProtocolUpdateValueObject as AnimalProtocolUpdateVO,
)


def make_animal_protocol_create(**overrides: Any) -> AnimalProtocolCreateVO:
    """Build an AnimalProtocolCreateValueObject."""
    defaults = dict(animal_id=uuid4())
    defaults.update(overrides)
    return AnimalProtocolCreateVO(**defaults)


def make_animal_protocol_entity(**overrides: Any) -> AnimalProtocolEntity:
    """Build an AnimalProtocolEntity with realistic defaults."""
    defaults = dict(
        id=uuid4(),
        animal=make_animal_entity(),
        vaccinated=False,
        vaccinated_date=None,
        sale_permission=False,
        sale_permission_date=None,
    )
    defaults.update(overrides)
    return AnimalProtocolEntity(**defaults)


def make_animal_protocol_list_params(**overrides: Any) -> AnimalProtocolListParamsVO:
    """Build AnimalProtocolListQueryParamsValueObject."""
    defaults: dict[str, Any] = {}
    defaults.update(overrides)
    return AnimalProtocolListParamsVO(**defaults)


def make_animal_protocol_update(**overrides: Any) -> AnimalProtocolUpdateVO:
    """Build an AnimalProtocolUpdateValueObject."""
    defaults = dict(user_id=uuid4(), vaccinated=False, vaccinated_date=None, sale_permission=False, sale_permission_date=None)
    defaults.update(overrides)
    return AnimalProtocolUpdateVO(**defaults)


# ── Cattle: Schedule Events ───────────────────────────────────────────

from src.cattle.domain.entities.schedule_events_entity import ScheduleEventEntity  # noqa: E402
from src.cattle.domain.value_objects.schedule_event_value_object import (  # noqa: E402
    ScheduleEventCreationValueObject,
    ScheduleEventsListQueryParamsValueObject as ScheduleEventListParamsVO,
    ScheduleEventUpdateValueObject,
)


def make_schedule_event_create(**overrides: Any) -> ScheduleEventCreationValueObject:
    """Build a ScheduleEventCreationValueObject."""
    defaults = dict(
        user_id=uuid4(),
        title=_faker.sentence(nb_words=4),
        description=_faker.sentence(nb_words=10),
        event_date=_faker.date_between(start_date="-1m", end_date="today"),
    )
    defaults.update(overrides)
    return ScheduleEventCreationValueObject(**defaults)


def make_schedule_event_entity(**overrides: Any) -> ScheduleEventEntity:
    """Build a ScheduleEventEntity with realistic defaults."""
    defaults = dict(
        id=uuid4(),
        user_id=uuid4(),
        created_at=datetime.now(tz=timezone.utc),
        title=_faker.sentence(nb_words=4),
        description=_faker.sentence(nb_words=10),
        event_date=_faker.date_between(start_date="-1m", end_date="today"),
        pending=True,
    )
    defaults.update(overrides)
    return ScheduleEventEntity(**defaults)


def make_schedule_event_list_params(**overrides: Any) -> ScheduleEventListParamsVO:
    """Build ScheduleEventsListQueryParamsValueObject."""
    defaults: dict[str, Any] = {}
    defaults.update(overrides)
    return ScheduleEventListParamsVO(**defaults)


def make_schedule_event_update(**overrides: Any) -> ScheduleEventUpdateValueObject:
    """Build a ScheduleEventUpdateValueObject."""
    defaults = dict(
        user_id=uuid4(),
        title=_faker.sentence(nb_words=4),
        description=_faker.sentence(nb_words=10),
        event_date=_faker.date_between(start_date="-1m", end_date="today"),
    )
    defaults.update(overrides)
    return ScheduleEventUpdateValueObject(**defaults)


# ── Finance: Purchases ────────────────────────────────────────────────

from src.finance.domain.constants.animal_supplies import UnitOfMeasurement  # noqa: E402
from src.finance.domain.entities.purchases import PurchaseEntity  # noqa: E402
from src.finance.domain.value_objects.purchase_value_objects import (  # noqa: E402
    PurchaseCreateValueObject as PurchaseCreateVO,
    PurchaseListQueryParamValueObject as PurchaseListParamsVO,
)


def make_purchase_create(**overrides: Any) -> PurchaseCreateVO:
    """Build a PurchaseCreateValueObject."""
    defaults = dict(
        user_id=uuid4(),
        supply_id=uuid4(),
        amount=round(float(_faker.pydecimal(min_value=1, max_value=100, right_digits=2)), 2),
        price=round(float(_faker.pydecimal(min_value=100, max_value=5000, right_digits=2)), 2),
        purchase_date=_faker.date_between(start_date="-1m", end_date="today"),
        unit_price=round(float(_faker.pydecimal(min_value=10, max_value=500, right_digits=2)), 2),
        unit_of_measurement=UnitOfMeasurement.KILOGRAMS,
    )
    defaults.update(overrides)
    return PurchaseCreateVO(**defaults)


def make_purchase_entity(**overrides: Any) -> PurchaseEntity:
    """Build a PurchaseEntity with realistic defaults."""
    defaults = dict(
        id=uuid4(),
        amount=round(float(_faker.pydecimal(min_value=1, max_value=100, right_digits=2)), 2),
        price=round(float(_faker.pydecimal(min_value=100, max_value=5000, right_digits=2)), 2),
        purchase_date=_faker.date_between(start_date="-1m", end_date="today"),
        unit_price=round(float(_faker.pydecimal(min_value=10, max_value=500, right_digits=2)), 2),
        unit_of_measurement=UnitOfMeasurement.KILOGRAMS,
        user_id=uuid4(),
        user_name=_faker.name(),
        supply_id=uuid4(),
        supply_name=_faker.unique.word(),
    )
    defaults.update(overrides)
    return PurchaseEntity(**defaults)


def make_purchase_list_params(**overrides: Any) -> PurchaseListParamsVO:
    """Build PurchaseListQueryParamValueObject."""
    defaults: dict[str, Any] = {}
    defaults.update(overrides)
    return PurchaseListParamsVO(**defaults)


# ── Finance: Animal Supplies ──────────────────────────────────────────

from src.finance.domain.entities.animal_supplies import AnimalSupplyEntity  # noqa: E402
from src.finance.domain.value_objects.animal_supplies_value_objects import (  # noqa: E402
    AnimalSuppliesCreateValueObject as AnimalSuppliesCreateVO,
    AnimalSuppliesListQueryParamsValueObject as AnimalSuppliesListParamsVO,
    AnimalSuppliesUpdateValueObject as AnimalSuppliesUpdateVO,
)


def make_animal_supply_create(**overrides: Any) -> AnimalSuppliesCreateVO:
    """Build an AnimalSuppliesCreateValueObject."""
    defaults = dict(
        type_id=uuid4(),
        user_id=uuid4(),
        name=_faker.unique.word(),
        amount=round(float(_faker.pydecimal(min_value=50, max_value=500, right_digits=2)), 2),
        critical_amount=round(float(_faker.pydecimal(min_value=5, max_value=25, right_digits=2)), 2),
        unit_of_measurement=UnitOfMeasurement.KILOGRAMS,
        description=_faker.sentence(nb_words=6),
    )
    defaults.update(overrides)
    return AnimalSuppliesCreateVO(**defaults)


def make_animal_supply_entity(**overrides: Any) -> AnimalSupplyEntity:
    """Build an AnimalSupplyEntity with realistic defaults."""
    defaults = dict(
        id=uuid4(),
        name=_faker.unique.word(),
        amount=round(float(_faker.pydecimal(min_value=50, max_value=500, right_digits=2)), 2),
        critical_amount=round(float(_faker.pydecimal(min_value=5, max_value=25, right_digits=2)), 2),
        unit_of_measurement=UnitOfMeasurement.KILOGRAMS,
        description=_faker.sentence(nb_words=6),
    )
    defaults.update(overrides)
    return AnimalSupplyEntity(**defaults)


def make_animal_supply_update(**overrides: Any) -> AnimalSuppliesUpdateVO:
    """Build an AnimalSuppliesUpdateValueObject."""
    defaults = dict(
        type_id=uuid4(),
        name=_faker.unique.word(),
        amount=round(float(_faker.pydecimal(min_value=50, max_value=500, right_digits=2)), 2),
        critical_amount=round(float(_faker.pydecimal(min_value=5, max_value=25, right_digits=2)), 2),
        unit_of_measurement=UnitOfMeasurement.KILOGRAMS,
    )
    defaults.update(overrides)
    return AnimalSuppliesUpdateVO(**defaults)


def make_animal_supply_list_params(**overrides: Any) -> AnimalSuppliesListParamsVO:
    """Build AnimalSuppliesListQueryParamsValueObject."""
    defaults: dict[str, Any] = {}
    defaults.update(overrides)
    return AnimalSuppliesListParamsVO(**defaults)


# ── Finance: Animal Supply Types ──────────────────────────────────────

from src.finance.domain.entities.animal_supplies import SupplyTypeEntity  # noqa: E402
from src.finance.domain.value_objects.animal_supply_type_value_objects import (  # noqa: E402
    AnimalSupplyTypeCreateValueObject as SupplyTypeCreateVO,
    AnimalSupplyTypeListQueryParamsValueObject as SupplyTypeListParamsVO,
    AnimalSupplyTypeUpdateValueObject as SupplyTypeUpdateVO,
)


def make_supply_type_create(**overrides: Any) -> SupplyTypeCreateVO:
    """Build an AnimalSupplyTypeCreateValueObject."""
    defaults = dict(name=_faker.unique.word())
    defaults.update(overrides)
    return SupplyTypeCreateVO(**defaults)


def make_supply_type_entity(**overrides: Any) -> SupplyTypeEntity:
    """Build a SupplyTypeEntity."""
    defaults = dict(id=uuid4(), name=_faker.unique.word())
    defaults.update(overrides)
    return SupplyTypeEntity(**defaults)


def make_supply_type_list_params(**overrides: Any) -> SupplyTypeListParamsVO:
    """Build AnimalSupplyTypeListQueryParamsValueObject."""
    defaults: dict[str, Any] = {}
    defaults.update(overrides)
    return SupplyTypeListParamsVO(**defaults)


def make_supply_type_update(**overrides: Any) -> SupplyTypeUpdateVO:
    """Build an AnimalSupplyTypeUpdateValueObject."""
    defaults = dict(name=_faker.unique.word())
    defaults.update(overrides)
    return SupplyTypeUpdateVO(**defaults)
