"""empty message

Revision ID: 3236232de2ec
Revises: 4f9ec048c063
Create Date: 2026-07-19 03:38:26.617986

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3236232de2ec"
down_revision: Union[str, None] = "4f9ec048c063"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_log_tenant_created_at"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_tenant_entity"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_user_id"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("tenant_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("action", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("entity_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("entity_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("old_values", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("new_values", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("ip_address", sa.VARCHAR(length=45), autoincrement=False, nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], name=op.f("audit_log_tenant_id_fkey"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("audit_log_user_id_fkey"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", "created_at", name=op.f("audit_log_pkey")),
    )
    op.create_index(op.f("ix_audit_log_user_id"), "audit_log", ["user_id"], unique=False)
    op.create_index(op.f("ix_audit_log_tenant_entity"), "audit_log", ["tenant_id", "entity_type", "entity_id"], unique=False)
    op.create_index(op.f("ix_audit_log_tenant_created_at"), "audit_log", ["tenant_id", sa.literal_column("created_at DESC")], unique=False)
    # ### end Alembic commands ###
