"""empty message

Revision ID: 34b510bc1534
Revises: c9e36f51ce2c
Create Date: 2026-09-15 21:22:35.981713

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34b510bc1534"
down_revision: Union[str, None] = "c9e36f51ce2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    calendar_event_type = sa.Enum(
        "vacunacion",
        "remate",
        "reunion",
        "veterinario",
        "pesaje",
        "marcado",
        "desparasitacion",
        "transporte",
        "otro",
        name="calendareventtype",
    )
    calendar_event_type.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "calendar_events",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pending", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("calendar_events", sa.Column("type", calendar_event_type, nullable=False))
    op.create_index(op.f("ix_calendar_events_end"), "calendar_events", ["end"], unique=False)
    op.create_index(op.f("ix_calendar_events_id"), "calendar_events", ["id"], unique=False)
    op.create_index(op.f("ix_calendar_events_start"), "calendar_events", ["start"], unique=False)
    op.create_index(op.f("ix_calendar_events_tenant_id"), "calendar_events", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_calendar_events_title"), "calendar_events", ["title"], unique=False)
    op.create_index(op.f("ix_calendar_events_type"), "calendar_events", ["type"], unique=False)
    op.create_table(
        "calendar_event_participants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["calendar_events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_id", "user_id"),
    )
    op.create_index(op.f("ix_calendar_event_participants_id"), "calendar_event_participants", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_calendar_event_participants_id"), table_name="calendar_event_participants")
    op.drop_table("calendar_event_participants")
    op.drop_index(op.f("ix_calendar_events_type"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_title"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_tenant_id"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_start"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_id"), table_name="calendar_events")
    op.drop_index(op.f("ix_calendar_events_end"), table_name="calendar_events")
    op.drop_table("calendar_events")
    # ### end Alembic commands ###
