"""empty message

Revision ID: 47b0cf3b3a09
Revises: 79dbe614a5ab
Create Date: 2026-09-04 12:43:40.937617

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47b0cf3b3a09"
down_revision: Union[str, None] = "79dbe614a5ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    animal_event_type = sa.Enum(
        "vacunacion",
        "remate",
        "reunion",
        "veterinario",
        "pesaje",
        "marcado",
        "desparasitacion",
        "transporte",
        name="animaleventtype",
    )
    animal_event_type.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduled_event_participants",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["scheduled_events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_id", "user_id", "id"),
    )
    op.create_index(op.f("ix_scheduled_event_participants_id"), "scheduled_event_participants", ["id"], unique=False)
    op.add_column("scheduled_events", sa.Column("type", animal_event_type, nullable=True))
    op.create_index(op.f("ix_scheduled_events_type"), "scheduled_events", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scheduled_events_type"), table_name="scheduled_events")
    op.drop_column("scheduled_events", "type")
    op.drop_index(op.f("ix_scheduled_event_participants_id"), table_name="scheduled_event_participants")
    op.drop_table("scheduled_event_participants")
    op.drop_column("scheduled_events", "type")
    sa.Enum(
        "vacunacion",
        "remate",
        "reunion",
        "veterinario",
        "pesaje",
        "marcado",
        "desparasitacion",
        "transporte",
        name="animaleventtype",
    ).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
