"""empty message

Revision ID: 4b13e5aa5223
Revises: 55dae3acf13c
Create Date: 2026-08-31 17:01:33.614619

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b13e5aa5223"
down_revision: Union[str, None] = "55dae3acf13c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scheduled_events", sa.Column("start", sa.DateTime(), nullable=False))
    op.add_column("scheduled_events", sa.Column("end", sa.DateTime(), nullable=False))
    op.drop_index(op.f("ix_scheduled_events_event_date"), table_name="scheduled_events")
    op.create_index(op.f("ix_scheduled_events_end"), "scheduled_events", ["end"], unique=False)
    op.create_index(op.f("ix_scheduled_events_start"), "scheduled_events", ["start"], unique=False)
    op.drop_column("scheduled_events", "event_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scheduled_events", sa.Column("event_date", sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f("ix_scheduled_events_start"), table_name="scheduled_events")
    op.drop_index(op.f("ix_scheduled_events_end"), table_name="scheduled_events")
    op.create_index(op.f("ix_scheduled_events_event_date"), "scheduled_events", ["event_date"], unique=False)
    op.drop_column("scheduled_events", "end")
    op.drop_column("scheduled_events", "start")
    # ### end Alembic commands ###
