"""empty message

Revision ID: 4f9ec048c063
Revises:
Create Date: 2026-07-18 23:36:04.782112

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4f9ec048c063"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "animal_supply_types",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_animal_supply_types_id"), "animal_supply_types", ["id"], unique=False)
    op.create_index(op.f("ix_animal_supply_types_name"), "animal_supply_types", ["name"], unique=True)
    op.create_table(
        "animal_types",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_animal_types_id"), "animal_types", ["id"], unique=False)
    op.create_index(op.f("ix_animal_types_name"), "animal_types", ["name"], unique=True)
    op.create_table(
        "event_outbox",
        sa.Column("event_id", sa.Uuid(), nullable=False, comment="The domain event's unique identifier (for tracing)."),
        sa.Column("event_type", sa.String(length=100), nullable=False, comment="Discriminator matching DomainEvent.event_type."),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False, comment="Aggregate that produced the event."),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Serialized event data forwarded to webhook subscribers.",
        ),
        sa.Column("status", sa.String(length=20), nullable=False, comment="PENDING | SENT | FAILED"),
        sa.Column("retry_count", sa.Integer(), nullable=False, comment="Number of delivery attempts."),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_outbox_id"), "event_outbox", ["id"], unique=False)
    op.create_index("ix_event_outbox_status_created_at", "event_outbox", ["status", "created_at"], unique=False)
    op.create_table(
        "plans",
        sa.Column("plan_type", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("quotas", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("price_monthly", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("price_yearly", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_type"),
    )
    op.create_index(op.f("ix_plans_id"), "plans", ["id"], unique=False)
    op.create_table(
        "webhook_subscriptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("secret", sa.String(length=100), nullable=False),
        sa.Column("subscribed_events", postgresql.ARRAY(sa.String(length=100)), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_webhook_subscriptions_tenant_id"), "webhook_subscriptions", ["tenant_id"], unique=False)
    op.create_table(
        "tenants",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenants_id"), "tenants", ["id"], unique=False)
    op.create_index(op.f("ix_tenants_name"), "tenants", ["name"], unique=False)
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_table(
        "subscriptions",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trial_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("mp_preference_id", sa.VARCHAR(length=255), nullable=True),
        sa.Column("mp_subscription_id", sa.VARCHAR(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subscriptions_id"), "subscriptions", ["id"], unique=False)
    op.create_index(op.f("ix_subscriptions_tenant_id"), "subscriptions", ["tenant_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("dni", sa.String(length=10), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_dni"), "users", ["dni"], unique=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_table(
        "animal_supplies",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("critical_amount", sa.Float(), nullable=False),
        sa.Column(
            "unit_of_measurement",
            sa.Enum(
                "KILOGRAMS", "GRAMS", "UNIT", "METERS", "CENTIMETERS", "LITERS", "MILILITERS", "CUBIC_CENTIMETERS", name="unitofmeasurement"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["type_id"], ["animal_supply_types.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_animal_supplies_id"), "animal_supplies", ["id"], unique=False)
    op.create_index(op.f("ix_animal_supplies_name"), "animal_supplies", ["name"], unique=False)
    op.create_index(op.f("ix_animal_supplies_tenant_id"), "animal_supplies", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_animal_supplies_user_id"), "animal_supplies", ["user_id"], unique=False)
    op.create_table(
        "animals",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type_id", sa.Uuid(), nullable=True),
        sa.Column("caravana", sa.String(length=50), nullable=False),
        sa.Column("tag", sa.String(length=50), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("initial_weight", sa.Float(), nullable=False),
        sa.Column("initial_weight_date", sa.Date(), nullable=False),
        sa.Column("last_weight", sa.Float(), nullable=False),
        sa.Column("breed", sa.String(length=50), nullable=False),
        sa.Column("status", sa.Enum("READY", "NOT_READY", "SOLD", name="animalstatus"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["type_id"], ["animal_types.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("caravana"),
    )
    op.create_index(op.f("ix_animals_id"), "animals", ["id"], unique=False)
    op.create_index(op.f("ix_animals_status"), "animals", ["status"], unique=False)
    op.create_index(op.f("ix_animals_tenant_id"), "animals", ["tenant_id"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("old_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", "created_at"),
        postgresql_partition_by="RANGE (created_at)",
    )
    op.create_index("ix_audit_log_tenant_created_at", "audit_log", ["tenant_id", sa.literal_column("created_at DESC")], unique=False)
    op.create_index("ix_audit_log_tenant_entity", "audit_log", ["tenant_id", "entity_type", "entity_id"], unique=False)
    op.create_index("ix_audit_log_user_id", "audit_log", ["user_id"], unique=False)
    op.create_table(
        "buyers",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("contact_number", sa.String(length=10), nullable=False),
        sa.Column("contact_address", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_buyers_id"), "buyers", ["id"], unique=False)
    op.create_index(op.f("ix_buyers_name"), "buyers", ["name"], unique=False)
    op.create_index(op.f("ix_buyers_tenant_id"), "buyers", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_buyers_user_id"), "buyers", ["user_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("mp_payment_id", sa.String(length=255), nullable=True),
        sa.Column("mp_preference_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("payment_method", sa.String(length=50), nullable=True),
        sa.Column("installments", sa.Integer(), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["subscription_id"], ["subscriptions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mp_payment_id"),
    )
    op.create_index(op.f("ix_payments_id"), "payments", ["id"], unique=False)
    op.create_index(op.f("ix_payments_subscription_id"), "payments", ["subscription_id"], unique=False)
    op.create_index(op.f("ix_payments_tenant_id"), "payments", ["tenant_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_refresh_tokens_family_id"), "refresh_tokens", ["family_id"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_id"), "refresh_tokens", ["id"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "scheduled_events",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("pending", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scheduled_events_event_date"), "scheduled_events", ["event_date"], unique=False)
    op.create_index(op.f("ix_scheduled_events_id"), "scheduled_events", ["id"], unique=False)
    op.create_index(op.f("ix_scheduled_events_tenant_id"), "scheduled_events", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_scheduled_events_title"), "scheduled_events", ["title"], unique=False)
    op.create_table(
        "animal_protocols",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("animal_id", sa.Uuid(), nullable=False),
        sa.Column("vaccinated", sa.Boolean(), nullable=False),
        sa.Column("vaccinated_date", sa.Date(), nullable=True),
        sa.Column("sale_permission", sa.Boolean(), nullable=False),
        sa.Column("sale_permission_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["animal_id"], ["animals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_animal_protocols_id"), "animal_protocols", ["id"], unique=False)
    op.create_index(op.f("ix_animal_protocols_tenant_id"), "animal_protocols", ["tenant_id"], unique=False)
    op.create_table(
        "purchases",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("supply_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("purchase_date", sa.Date(), nullable=False),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.Column(
            "unit_of_measurement",
            sa.Enum(
                "KILOGRAMS", "GRAMS", "UNIT", "METERS", "CENTIMETERS", "LITERS", "MILILITERS", "CUBIC_CENTIMETERS", name="unitofmeasurement"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["supply_id"], ["animal_supplies.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_purchases_id"), "purchases", ["id"], unique=False)
    op.create_index(op.f("ix_purchases_supply_id"), "purchases", ["supply_id"], unique=False)
    op.create_index(op.f("ix_purchases_tenant_id"), "purchases", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_purchases_user_id"), "purchases", ["user_id"], unique=False)
    op.create_table(
        "sales",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("buyer_id", sa.Uuid(), nullable=False),
        sa.Column("animal_id", sa.Uuid(), nullable=False),
        sa.Column("sale_date", sa.DateTime(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("price_per_kg", sa.Float(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["animal_id"], ["animals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["buyer_id"], ["buyers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sales_animal_id"), "sales", ["animal_id"], unique=False)
    op.create_index(op.f("ix_sales_buyer_id"), "sales", ["buyer_id"], unique=False)
    op.create_index(op.f("ix_sales_id"), "sales", ["id"], unique=False)
    op.create_index(op.f("ix_sales_tenant_id"), "sales", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_sales_user_id"), "sales", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sales_user_id"), table_name="sales")
    op.drop_index(op.f("ix_sales_tenant_id"), table_name="sales")
    op.drop_index(op.f("ix_sales_id"), table_name="sales")
    op.drop_index(op.f("ix_sales_buyer_id"), table_name="sales")
    op.drop_index(op.f("ix_sales_animal_id"), table_name="sales")
    op.drop_table("sales")
    op.drop_index(op.f("ix_purchases_user_id"), table_name="purchases")
    op.drop_index(op.f("ix_purchases_tenant_id"), table_name="purchases")
    op.drop_index(op.f("ix_purchases_supply_id"), table_name="purchases")
    op.drop_index(op.f("ix_purchases_id"), table_name="purchases")
    op.drop_table("purchases")
    op.drop_index(op.f("ix_animal_protocols_tenant_id"), table_name="animal_protocols")
    op.drop_index(op.f("ix_animal_protocols_id"), table_name="animal_protocols")
    op.drop_table("animal_protocols")
    op.drop_index(op.f("ix_scheduled_events_title"), table_name="scheduled_events")
    op.drop_index(op.f("ix_scheduled_events_tenant_id"), table_name="scheduled_events")
    op.drop_index(op.f("ix_scheduled_events_id"), table_name="scheduled_events")
    op.drop_index(op.f("ix_scheduled_events_event_date"), table_name="scheduled_events")
    op.drop_table("scheduled_events")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_payments_tenant_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_subscription_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_buyers_user_id"), table_name="buyers")
    op.drop_index(op.f("ix_buyers_tenant_id"), table_name="buyers")
    op.drop_index(op.f("ix_buyers_name"), table_name="buyers")
    op.drop_index(op.f("ix_buyers_id"), table_name="buyers")
    op.drop_table("buyers")
    op.drop_index("ix_audit_log_user_id", table_name="audit_log")
    op.drop_index("ix_audit_log_tenant_entity", table_name="audit_log")
    op.drop_index("ix_audit_log_tenant_created_at", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_animals_tenant_id"), table_name="animals")
    op.drop_index(op.f("ix_animals_status"), table_name="animals")
    op.drop_index(op.f("ix_animals_id"), table_name="animals")
    op.drop_table("animals")
    op.drop_index(op.f("ix_animal_supplies_user_id"), table_name="animal_supplies")
    op.drop_index(op.f("ix_animal_supplies_tenant_id"), table_name="animal_supplies")
    op.drop_index(op.f("ix_animal_supplies_name"), table_name="animal_supplies")
    op.drop_index(op.f("ix_animal_supplies_id"), table_name="animal_supplies")
    op.drop_table("animal_supplies")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_dni"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_subscriptions_tenant_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_name"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_id"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_index(op.f("ix_webhook_subscriptions_tenant_id"), table_name="webhook_subscriptions")
    op.drop_table("webhook_subscriptions")
    op.drop_index(op.f("ix_plans_id"), table_name="plans")
    op.drop_table("plans")
    op.drop_index("ix_event_outbox_status_created_at", table_name="event_outbox")
    op.drop_index(op.f("ix_event_outbox_id"), table_name="event_outbox")
    op.drop_table("event_outbox")
    op.drop_index(op.f("ix_animal_types_name"), table_name="animal_types")
    op.drop_index(op.f("ix_animal_types_id"), table_name="animal_types")
    op.drop_table("animal_types")
    op.drop_index(op.f("ix_animal_supply_types_name"), table_name="animal_supply_types")
    op.drop_index(op.f("ix_animal_supply_types_id"), table_name="animal_supply_types")
    op.drop_table("animal_supply_types")
    # ### end Alembic commands ###
