"""empty message

Revision ID: 55dae3acf13c
Revises: fdecabde8e2f
Create Date: 2026-08-03 12:01:41.944901

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "55dae3acf13c"
down_revision: Union[str, None] = "fdecabde8e2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
