"""empty message

Revision ID: 58ec64fc1c38
Revises: a1b2c3d4e5f6
Create Date: 2026-07-24 04:47:25.995967

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58ec64fc1c38"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_animals_tenant_status"), table_name="animals")
    op.drop_constraint(op.f("audit_log_tenant_id_fkey"), "audit_log", type_="foreignkey")
    op.create_foreign_key(None, "audit_log", "tenants", ["tenant_id"], ["id"], ondelete="SET NULL")
    op.drop_index(op.f("ix_sales_tenant_sale_date"), table_name="sales")
    op.add_column("subscriptions", sa.Column("billing_date", sa.DateTime(timezone=True), nullable=True))
    op.add_column("subscriptions", sa.Column("next_billing_date", sa.DateTime(timezone=True), nullable=True))
    op.add_column("subscriptions", sa.Column("mp_card_id", sa.VARCHAR(length=10), nullable=True))
    op.create_foreign_key(None, "webhook_subscriptions", "tenants", ["tenant_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "webhook_subscriptions", type_="foreignkey")
    op.drop_column("subscriptions", "mp_card_id")
    op.drop_column("subscriptions", "next_billing_date")
    op.drop_column("subscriptions", "billing_date")
    op.create_index(op.f("ix_sales_tenant_sale_date"), "sales", ["tenant_id", "sale_date"], unique=False)
    op.drop_constraint(None, "audit_log", type_="foreignkey")
    op.create_foreign_key(op.f("audit_log_tenant_id_fkey"), "audit_log", "tenants", ["tenant_id"], ["id"], ondelete="CASCADE")
    op.create_index(op.f("ix_animals_tenant_status"), "animals", ["tenant_id", "status"], unique=False)
    # ### end Alembic commands ###
