"""empty message

Revision ID: 6a09247abd48
Revises: 47b0cf3b3a09
Create Date: 2026-09-04 13:01:10.001576

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6a09247abd48"
down_revision: Union[str, None] = "47b0cf3b3a09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scheduled_events",
        "type",
        existing_type=postgresql.ENUM(
            "vacunacion", "remate", "reunion", "veterinario", "pesaje", "marcado", "desparasitacion", "transporte", name="animaleventtype"
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scheduled_events",
        "type",
        existing_type=postgresql.ENUM(
            "vacunacion", "remate", "reunion", "veterinario", "pesaje", "marcado", "desparasitacion", "transporte", name="animaleventtype"
        ),
        nullable=True,
    )
    # ### end Alembic commands ###
