"""empty message

Revision ID: 803c5d93bfda
Revises: 8a20e2cebe6b
Create Date: 2026-09-04 19:27:14.484438

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "803c5d93bfda"
down_revision: Union[str, None] = "8a20e2cebe6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scheduled_event_participants_id"), table_name="scheduled_event_participants")
    op.create_index(op.f("ix_scheduled_event_participants_id"), "scheduled_event_participants", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scheduled_event_participants_id"), table_name="scheduled_event_participants")
    op.create_index(op.f("ix_scheduled_event_participants_id"), "scheduled_event_participants", ["id"], unique=False)
    # ### end Alembic commands ###
