"""empty message

Revision ID: 8a20e2cebe6b
Revises: 6a09247abd48
Create Date: 2026-09-04 13:04:01.010863

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a20e2cebe6b"
down_revision: Union[str, None] = "6a09247abd48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE animaleventtype ADD VALUE 'otro'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE animaleventtype DROP VALUE 'otro'")
    # ### end Alembic commands ###
