"""empty message

Revision ID: c58a6670b213
Revises: df1c3ae4f2b6
Create Date: 2026-09-04 19:36:43.741832

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c58a6670b213"
down_revision: Union[str, None] = "df1c3ae4f2b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
