"""empty message

Revision ID: df1c3ae4f2b6
Revises: 803c5d93bfda
Create Date: 2026-09-04 19:35:30.247729

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "df1c3ae4f2b6"
down_revision: Union[str, None] = "803c5d93bfda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scheduled_event_participants_id"), table_name="scheduled_event_participants")
    op.drop_table("scheduled_event_participants")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduled_event_participants",
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["scheduled_events.id"], name=op.f("scheduled_event_participants_event_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("scheduled_event_participants_user_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_id", "user_id", "id", name=op.f("scheduled_event_participants_pkey")),
    )
    op.create_index(op.f("ix_scheduled_event_participants_id"), "scheduled_event_participants", ["id"], unique=True)
    # ### end Alembic commands ###
