"""empty message

Revision ID: ee522a9be72a
Revises: 34b510bc1534
Create Date: 2026-09-15 21:55:11.643233

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ee522a9be72a"
down_revision: Union[str, None] = "34b510bc1534"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scheduled_event_participants_id"), table_name="scheduled_event_participants")
    op.drop_table("scheduled_event_participants")
    op.drop_index(op.f("ix_scheduled_events_end"), table_name="scheduled_events")
    op.drop_index(op.f("ix_scheduled_events_id"), table_name="scheduled_events")
    op.drop_index(op.f("ix_scheduled_events_start"), table_name="scheduled_events")
    op.drop_index(op.f("ix_scheduled_events_tenant_id"), table_name="scheduled_events")
    op.drop_index(op.f("ix_scheduled_events_title"), table_name="scheduled_events")
    op.drop_index(op.f("ix_scheduled_events_type"), table_name="scheduled_events")
    op.drop_table("scheduled_events")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduled_events",
        sa.Column("tenant_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("pending", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("start", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("end", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "vacunacion",
                "remate",
                "reunion",
                "veterinario",
                "pesaje",
                "marcado",
                "desparasitacion",
                "transporte",
                "otro",
                name="animaleventtype",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], name=op.f("scheduled_events_tenant_id_fkey"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("scheduled_events_user_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("scheduled_events_pkey")),
    )
    op.create_index(op.f("ix_scheduled_events_type"), "scheduled_events", ["type"], unique=False)
    op.create_index(op.f("ix_scheduled_events_title"), "scheduled_events", ["title"], unique=False)
    op.create_index(op.f("ix_scheduled_events_tenant_id"), "scheduled_events", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_scheduled_events_start"), "scheduled_events", ["start"], unique=False)
    op.create_index(op.f("ix_scheduled_events_id"), "scheduled_events", ["id"], unique=False)
    op.create_index(op.f("ix_scheduled_events_end"), "scheduled_events", ["end"], unique=False)
    op.create_table(
        "scheduled_event_participants",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["scheduled_events.id"], name=op.f("scheduled_event_participants_event_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("scheduled_event_participants_user_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_id", "user_id", name=op.f("scheduled_event_participants_pkey")),
    )
    op.create_index(op.f("ix_scheduled_event_participants_id"), "scheduled_event_participants", ["id"], unique=True)
    # ### end Alembic commands ###
