"""empty message

Revision ID: fdecabde8e2f
Revises: 58ec64fc1c38
Create Date: 2026-08-03 11:59:48.618258

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fdecabde8e2f"
down_revision: Union[str, None] = "58ec64fc1c38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("sales", "sale_date", existing_type=postgresql.TIMESTAMP(), type_=sa.Date(), existing_nullable=False)
    op.alter_column("subscriptions", "mp_card_id", existing_type=sa.VARCHAR(length=10), type_=sa.VARCHAR(length=50), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("subscriptions", "mp_card_id", existing_type=sa.VARCHAR(length=50), type_=sa.VARCHAR(length=10), existing_nullable=True)
    op.alter_column("sales", "sale_date", existing_type=sa.Date(), type_=postgresql.TIMESTAMP(), existing_nullable=False)
    # ### end Alembic commands ###
